export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",

  // login: "Shahadat-Hossen-Pabel",
  // id: 57044325,
  // node_id: "MDQ6VXNlcjU3MDQ0MzI1",
  // avatar_url: "https://avatars.githubusercontent.com/u/57044325?v=4",
  // gravatar_id: "",
  // url: "https://api.github.com/users/Shahadat-Hossen-Pabel",
  // html_url: "https://github.com/Shahadat-Hossen-Pabel",
  // followers_url: "https://api.github.com/users/Shahadat-Hossen-Pabel/followers",
  // following_url:
  //   "https://api.github.com/users/Shahadat-Hossen-Pabel/following{/other_user}",
  // gists_url:
  //   "https://api.github.com/users/Shahadat-Hossen-Pabel/gists{/gist_id}",
  // starred_url:
  //   "https://api.github.com/users/Shahadat-Hossen-Pabel/starred{/owner}{/repo}",
  // subscriptions_url:
  //   "https://api.github.com/users/Shahadat-Hossen-Pabel/subscriptions",
  // organizations_url: "https://api.github.com/users/Shahadat-Hossen-Pabel/orgs",
  // repos_url: "https://api.github.com/users/Shahadat-Hossen-Pabel/repos",
  // events_url:
  //   "https://api.github.com/users/Shahadat-Hossen-Pabel/events{/privacy}",
  // received_events_url:
  //   "https://api.github.com/users/Shahadat-Hossen-Pabel/received_events",
  // type: "User",
  // site_admin: false,
  // name: "Shahadat Hossen",
  // company: "Rising Programmers",
  // blog: "www.risingprogrammers.com",
  // location: "Dhaka,Bangladesh",
  // email: null,
  // hireable: true,
  // bio:
  //   "Hi i,m Shahadat Hossen Pabel.i,m Website designer and developer. like to face challenges in field of coding and web development.",
  // twitter_username: "Shahada32499541",
  // public_repos: 3,
  // public_gists: 0,
  // followers: 1,
  // following: 1,
  // created_at: "2019-10-26T17:21:51Z",
  // updated_at: "2021-01-31T09:31:57Z",
};
